In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [18]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr.ndim) # Dimension of the array

[[1 2 3]
 [4 5 6]]
2


In [19]:
# Array indexing and slicing
arr = np.array([1, 2, 3, 4])
print(arr[2] + arr[3]) 

7


In [6]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr.shape)
print(arr[0, 1,2])

(2, 2, 3)
6


In [8]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[::2])
print(arr[-4:-1])


[1 3 5 7]
[4 5 6]


In [14]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])
print(arr[0:2, 1:4])
print(arr.shape)

[7 8 9]
[[2 3 4]
 [7 8 9]]
(2, 5)


In [20]:
# Typer convertion of array elements
arr = np.array([1.1, 2.1, 3.1])
narr = arr.astype('i')
print(narr)
print(narr.dtype)

[1 2 3]
int32


In [12]:
arr = np.array([1, 0, 3, 0])
narr = arr.astype(bool)
print(narr)

[ True False  True False]


In [21]:
arr = np.array([1, 2, 3, 4, 5, 6])
narr = arr.reshape(2, 3) # Reshaping arrays
print(narr)

[[1 2 3]
 [4 5 6]]


In [17]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
narr = arr.reshape(2, 3, 2)
print(narr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [22]:
# Copy vs View
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 10
print(arr)
print(x)

[10  2  3  4  5]
[1 2 3 4 5]


In [23]:
# Copy vs View
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 10
print(arr)
print(x)

[10  2  3  4  5]
[10  2  3  4  5]


In [25]:
# Flattening the array
arr = np.array([[1, 2, 3], [4, 5, 6]])
narr = arr. reshape(-1)
print(narr)

[1 2 3 4 5 6]


In [26]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [28]:
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [29]:
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6


In [32]:
# Converting data type while iterating
for x in np.nditer(arr, flags = ['buffered'], op_dtypes = ['float']):
    print(x)

1.0
2.0
3.0
4.0
5.0
6.0


In [34]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
narr = np.concatenate((arr1, arr2))
print(narr)

[1 2 3 4 5 6 7 8]


In [35]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
narr= np.concatenate((arr1, arr2), axis = 1)
print(narr)

[[1 2 5 6]
 [3 4 7 8]]


In [36]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
narr= np.concatenate((arr1, arr2), axis = 0)
print(narr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [37]:
arr = np.array([[3, 9, 1], [1, 0, 5]])
print(np.sort(arr))

[[1 3 9]
 [0 1 5]]
